version: '3'

services:
  learn-ml:
    image: tensorflow/tensorflow
    volumes:
      - "./src:/app"
      - "./output:/output"
      - "./requirements.txt:/tmp/requirements.txt"
    working_dir: "/app"
    tty: true
    command: >
        /bin/sh -c "
        pip install -r /tmp/requirements.txt;
        python -u main.py;"
